#!/bin/bash
set -euo pipefail
. /.functions

# List the artifacts or directories in the given URL
URL="${DEPL_URL}/global-sums"

wait-for-artifacts &>/dev/null || fail "Timed out waiting for the artifacts to become available at [${DEPL_URL}]"

JSON="$(curl -fsSL "${URL}")" || fail "Failed to retrieve the global artifact sums (rc = ${?})"

# Verify that it's JSON output
jq -r <<< "${JSON}" &>/dev/null || fail "The global artifacts sums data is not proper JSON:\n${JSON}"

echo -n "${JSON}"
