#!/bin/bash
set -euo pipefail

[ -v DEPL_URL ] || DEPL_URL="http://app-deploy"

say() {
	echo -e "$(date -u -Ins): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

cleanup() {
	[ -v OUT_DIR ] && [ -d "${OUT_DIR}" ] && rm -rf "${OUT_DIR}" &>/dev/null
}

usage() {
	echo -e "usage: ${BASH_SOURCE:-${0}} [category-path]" 1>&2
	exit 1
}

[ ${#} -le 1 ] || usage

TARGET_PATH="${1:-""}"

# Remove leading and trailing slashes
[[ "${TARGET_PATH}" =~ ^/*(.*[^/])/*$ ]] && TARGET_PATH="${BASH_REMATCH[1]}"

# Replace consecutive slashes
TARGET_PATH="$(echo -n "${TARGET_PATH}" | sed -e 's;/+;/;g')"

# URL-escape all path components
IFS="/" read -a PARTS <<< "${TARGET_PATH}"
TARGET_PATH=""
for P in "${PARTS[@]}" ; do
    [ -z "${TARGET_PATH}" ] || TARGET_PATH+="/"
    TARGET_PATH+="$(echo -n "${P}" | jq -sRr @uri)"
done

# List the artifacts or directories in the given URL
URL="${DEPL_URL}/api/1/${TARGET_PATH}"

JSON="$(curl -kL -s "${URL}?cmd=list")"

# Is the request successful?
STATUS="$(jq -r .rc <<< "${JSON}")"

# If the directory isn't found, just quit without output
[ ${STATUS} == 404 ] && exit 1

# If it's something else, then explode loudly while reporting the issue
[ ${STATUS} == 200 ] || fail "Failed to list the contents of [${TARGET_PATH}] (STATUS=${STATUS}):\n${JSON}"

# List the files contained within, including the path prefix
[ -n "${TARGET_PATH}" ] && TARGET_PATH="/${TARGET_PATH}"
jq -r ".data.files[] | .name" <<< "${JSON}" | \
	egrep -vi '\.ver' | \
	egrep -vi '\.sum' | \
	sed -e "s;^;${TARGET_PATH}/;g" | \
	sort -u
